matrix:
    RELEASE_TARGET:
        - x86_64-unknown-linux-musl
        - x86_64-apple-darwin

pipeline:
    assembleRelease:
        when:
            event: tag
        image: rust:1-alpine
        pull: true
        commands:
            ci/build_release.sh ${RELEASE_TARGET}
    addBinariesToRelease:
        when:
            event: tag
        image: plugins/gitea-release
        pull: true
        settings:
            base_url: https://codeberg.org
            api_key:
                from_secret: api_token
            files:
                - kak-dap-x86_64-unknown-linux-musl.tar.gz
                - kak-dap-x86_64-apple-darwin.tar.gz
