configurations:
  test:
    adapter: debugpy
    launch_args:
      program: ${CUR_DIR}/test.py
      args: []
      stopOnEntry: true
      console: externalTerminal
      debugOptions: []
      cwd: ${CUR_DIR}
  multithreaded_test:
    adapter: debugpy
    launch_args:
      program: ${CUR_DIR}/multithreaded_test.py
      args: []
      stopOnEntry: false
      console: externalTerminal
      debugOptions: []
      cwd: ${CUR_DIR}
