configurations:
    test_gdb:
        adapter: 'cpptools'
        launch_args:
            program: '${CUR_DIR}/test_c'
            args: []
            cwd: "${CUR_DIR}"
            externalConsole: false
            MIMode: "gdb"
            logging:
                programOutput: false
            stopAtEntry: true
            setupCommands:
            - text: "set startup-with-shell off" # This fixes issues GDB has with some shells
            - text: "-enable-pretty-printing" # This enables more ergonomic view of strings
    test_lldb:
        adapter: 'cpptools'
        launch_args:
            program: '${CUR_DIR}/test_c'
            args: []
            cwd: "${CUR_DIR}"
            externalConsole: false
            MIMode: "lldb"
            logging:
                programOutput: false
            stopAtEntry: true

